theme:
  #file: /an/absoulute/path/to/the/theme.yaml # if set, it will ignore everything below
  #bar:
    #color: '#4776E6' # basic color of the progressbar
    #gradient: '#ff0000' # if passed, will generate a gradient from previous color to this one
  graph:
    # see: https://pkg.go.dev/github.com/guptarohit/asciigraph#AnsiColor
    # see: https://github.com/guptarohit/asciigraph/blob/master/color.go#L152-L292
    #color: blue # does not use rgb but rather ANSI codes
    height: 0   # height of the graph
  #text:
    #error: # color when misspelled
      #background: '#f33'
      #foreground: '#fff'
    #typed: # color when character have been typed
      #foreground: '#fff'
      #background: '#000' # optional, default theme does not add background
    #untyped: # color when still haven't been typed
      #foreground: '#555'
      #background: '#000' # optional, default theme does not add background

