return {
    name = '+telescope', -- optional group name
    [' '] = {':Telescope', 'Telescope'},
    b = {',tb', 'Buffer in buffers'},
    B = {',tB', 'Find in buffers'},
    d = {',td', 'Diagnostics'},
    e = {',te', 'File explorer'},
    E = {',tE', 'Find in emojis'},
    f = {',tf', 'File in pwd'},
    F = {',tF', 'Find in files in pwd'},
    g = {',tg', 'Find file in git project'},
    h = {',th', 'Find in help tags'},
    I = {',tI', 'Find lsp implementations'},
    m = {',tm', 'Find in harpoon marks'},
    q = {',tq', 'Find in quickfix list'},
    r = {',tr', 'Find in refactor actions'},
    R = {',tR', 'Find lsp references'},
    s = {',ts', 'Find in lsp document symbols'},
    S = {',tS', 'Find in lsp workspace symbols'},
    t = {',tt', 'Find in treesitter'},
}
