alias cat "bat -pp --theme ansi"
alias cd "z"
alias du "dust"
alias find "fd"
alias grep "rg"
alias ld "lazydocker"
alias lg "lazygit"
alias ls "exa -al --icons"
alias ps "procs"
alias sed "sd"
# alias nnn "nnn -P p"
alias ssh "kitty +kitten ssh"
