require('settings')
require('cmds')
require('hooks')
require('keybindings')
require('plugins')
require('theme')
require('theme_overwrites')
-- require('theme_overwrites_horizon')
-- require('theme_overwrites_base2tone_evening')
